### ISSUE TITLE
Unable to load lvm attributes [lvs.yaml] for version [2.02.188(2)]

### ISSUE THREAD

**Issue by computersalat** [sous-chefs/chef-ruby-lvm-attrib#37]
Can you please
- **Add 2.02.188(2) attributes**

**Comment by roee73** [comment]
I created PR for this.
Waiting for Chef team review
https://github.com/chef/chef-ruby-lvm-attrib/pull/39

**Comment by computersalat** [comment]
as #39 got merged we can close this.
@RoeeFabrikant 
Thank you :-)
