### ISSUE TITLE
Release new gem that has attribute for LVM v2.03.14

### ISSUE THREAD

**Issue by HarshRajIN** [sous-chefs/chef-ruby-lvm-attrib#43]
I see that the attributes for LVM v2.03.14 was added to the repository but the new gem is not released yet.

Could someone please release the new gem that would support the newly added attributes.

We are running into issues because of unavailability of this attribute-

> Unable to load lvm attributes [lvs.yaml] for version [2.03.14(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-ruby-lvm-attrib-0.3.9/lib/lvm/attributes/2.03.14(2)/lvs.yaml]

**Comment by HarshRajIN** [comment]
Looks like the required [gem](https://rubygems.org/gems/chef-ruby-lvm-attrib/versions/0.3.10) was released but it's not tagged on the github.
For some reason, this gem is not being pulled up

**Comment by computersalat** [comment]
@ramereth 
 ... can we please have a new release that also contains
```
lvm attributes [lvs.yaml] for version [2.02.188(2)]
```
Thank you

**Comment by ramereth** [comment]
I have released 0.3.11 which should include this. Please confirm?

**Comment by computersalat** [comment]
> I have released 0.3.11 which should include this. Please confirm?

confirmed :+1:
