### ISSUE TITLE
RHEL 9.2 uses LVM 2.03.17 please update

### ISSUE THREAD

**Issue by lukeskaivolker** [sous-chefs/chef-ruby-lvm-attrib#50]
Describe the Enhancement:
RHEL 9.2 uses LVM 2.03.17

Describe the Need:
Support for latest LVM

Current Alternative
No

Can We Help You Implement This?:
Update latest version support

**Comment by lukeskaivolker** [comment]
# rpm -q lvm2
lvm2-2.03.17-7.el9.x86_64

**Comment by lukeskaivolker** [comment]
Unable to load lvm attributes [lvs.yaml] for version [2.03.17(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem

**Comment by mrhilly** [comment]
Waiting on this update also? Thanks!

**Comment by RoeeFabrikant** [comment]
I have created PR for this today:
https://github.com/sous-chefs/chef-ruby-lvm-attrib/pull/53 

I hope someone will merge it soon

**Comment by Stromweld** [comment]
closing this as completed with #53
