### ISSUE TITLE
Latest Gem isn't available on rubygems.org - Needed by LVM cookbook

### ISSUE THREAD

**Issue by davidjkling** [sous-chefs/chef-ruby-lvm-attrib#58]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Per the lvm cookbook update:
https://github.com/sous-chefs/lvm/blob/main/CHANGELOG.md#6118---2024-04-30

It requires the `chef-ruby-lvm-attrib 0.3.15` gem version, however, when using [6.1.20 of that cookbook](https://supermarket.chef.io/cookbooks/lvm/versions/6.1.20), it can't find the gem required:
https://rubygems.org/gems/chef-ruby-lvm-attrib/versions
![image](https://github.com/sous-chefs/chef-ruby-lvm-attrib/assets/44037307/b968794e-fef5-4d41-b471-7a349a63efbe)

```
    STDERR: ERROR:  Could not find a valid gem 'chef-ruby-lvm-attrib' (= 0.3.15) in any repository
```

## :pancakes: Cookbook version

Version of the cookbook where you are encountering the issue.
6.1.20 lvm cookbook

## :woman_cook:  Chef-Infra Version

Version of chef-client in your environment.
Chef 18.2.7

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by damacus** [comment]
Fixed :) 

Sorry about that!
